---
- name: Solve Lab 3
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
  - ../vars.yml
      
  tasks:
    - name: set catalog triggers to manual
      shell: "oc set triggers dc/catalog --manual -n {{ dev_project }}"
      ignore_errors: true

    - name: deploy jenkins in {{ cicd_project }}
      shell: "oc new-app jenkins-persistent -n {{ cicd_project }}"
      ignore_errors: true

    - name: create temporary git directory
      tempfile:
        state: directory
        prefix: catalog-git
      register: git_dir

    - name: clone catalog-spring-boot git repository to {{ git_dir.path }}
      shell: "git clone http://{{ gogs_user }}:{{ gogs_password }}@{{ gogs_hostname }}/{{ gogs_user }}/catalog-spring-boot.git"
      args:
        chdir: "{{ git_dir.path }}"

    - name: create jenkinsfile
      copy:
        src: Jenkinsfile
        dest: "{{ git_dir.path }}/catalog-spring-boot/Jenkinsfile"

    - name: push jenkinsfile to catalog-spring-boot git repository
      shell: |
        git add Jenkinsfile
        git commit -m "build pipeline added"
        git push origin master
      args:
        chdir: "{{ git_dir.path }}/catalog-spring-boot"

    - name: process build pipeline template
      template:
        src: pipeline.yml.j2
        dest: "{{ git_dir.path }}/pipelne.yml"

    - name: create build pipeline
      shell: "oc create -f {{ git_dir.path }}/pipelne.yml -n {{ cicd_project}}"
      ignore_errors: true