---
- name: Solve Lab 7
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
  - ../vars.yml
      
  tasks:
    - name: create prod credentials secret
      shell: |
        oc create secret generic prod-credentials --from-literal=username=openshift --from-literal=password={{ prod_token }} -n {{ cicd_project}}
        oc label secret prod-credentials credential.sync.jenkins.openshift.io=true -n {{ cicd_project}}
      ignore_errors: true

    - name: create temporary git directory
      tempfile:
        state: directory
        prefix: catalog-git
      register: git_dir

    - name: clone catalog-spring-boot git repository to {{ git_dir.path }}
      shell: "git clone http://{{ gogs_user }}:{{ gogs_password }}@{{ gogs_hostname }}/{{ gogs_user }}/catalog-spring-boot.git"
      args:
        chdir: "{{ git_dir.path }}"

    - name: create release jenkinsfile
      copy:
        src: Jenkinsfile.create-prod
        dest: "{{ git_dir.path }}/catalog-spring-boot/Jenkinsfile.create-prod"

    - name: push release jenkinsfile to catalog-spring-boot git repository
      shell: |
        git add Jenkinsfile.create-prod
        git commit -m "create prod pipeline added"
        git push origin master
      args:
        chdir: "{{ git_dir.path }}/catalog-spring-boot"

    - name: process create prod pipeline template
      template:
        src: pipeline.yml.j2
        dest: "{{ git_dir.path }}/pipelne.yml"

    - name: create prod pipeline
      shell: "oc create -f {{ git_dir.path }}/pipelne.yml -n {{ cicd_project}}"
      ignore_errors: true
