language: java

jdk:
  - oraclejdk8

before_install:
  - nvm install 4.4
  - cp .travis.settings.xml $HOME/.m2/settings.xml

env:
  - BUILD_CMD="mvn -f catalog-spring-boot package"
  - BUILD_CMD="npm install --prefix web-nodejs"

script:
  - $BUILD_CMD