---
- name: Solve Lab 1
  hosts: localhost
  gather_facts: false
  run_once: true
  vars:
    infra_project: lab-infra
      
  tasks:
    - name: solve
      shell: "oc get projects"
      ignore_errors: true
      changed_when: false