---
- name: Solve Lab 2
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
  - ../vars.yml
      
  tasks:
    - name: create catalog and web imagestreams in {{ cicd_project }}
      shell: "oc create -f https://raw.githubusercontent.com/{{ github_account }}/devops-oab-labs/{{ github_ref }}/openshift/catalog-is.yaml -n {{ cicd_project }}"
      ignore_errors: true

    - name: deploy web in {{ dev_project }}
      shell: |
        oc new-app -f https://raw.githubusercontent.com/{{ github_account }}/devops-oab-labs/{{ github_ref }}/openshift/web-template.yaml \
              --param=IMAGE_NAMESPACE={{ cicd_project }} \
              -n {{ dev_project }}
      ignore_errors: true

    - name: deploy catalog in {{ dev_project }}
      shell: |
        oc new-app -f https://raw.githubusercontent.com/{{ github_account }}/devops-oab-labs/{{ github_ref }}/openshift/catalog-template.yaml \
              --param=GIT_URI=http://{{ gogs_hostname }}/{{ gogs_user }}/catalog-spring-boot.git \
              --param=MAVEN_MIRROR_URL=http://nexus.{{ infra_project }}.svc:8081/repository/maven-all-public/ \
              --param=IMAGE_NAMESPACE={{ cicd_project }} \
              -n {{ dev_project }}
      ignore_errors: true

