---
- name: Solve Lab 4
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
  - ../vars.yml
      
  tasks:
    - name: extract webhook secret
      shell: |
        oc get bc catalog-build -o=jsonpath='{.spec.triggers[?(@.type=="Generic")].generic.secret}' -n {{ cicd_project}}
      register: webhook_secret_result

    - name: create webhook
      uri:
        url: http://{{ gogs_hostname }}/api/v1/repos/{{ gogs_user }}/catalog-spring-boot/hooks
        method: POST
        body: >
          {
            "type": "gogs",
            "config": {
              "url": "{{ openshift_master }}/oapi/v1/namespaces/{{ cicd_project }}/buildconfigs/catalog-build/webhooks/{{ webhook_secret_result.stdout }}/generic",
              "content_type": "json"
            },
            "events": [
              "push"
            ],
            "active": true
          }
        body_format: json
        user: "{{ gogs_user }}"
        password: "{{ gogs_password }}"
        status_code: 200,201
        force_basic_auth: true