- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: catalog
    labels:
      app: catalog
      application: coolstore
      component: catalog
  data:
    application.properties: |-
      spring.datasource.url=jdbc:mysql://${APB_DB_SERVICE_NAME}:${APB_DB_SERVICE_PORT}/${APB_DB_NAME}?useSSL=false
      spring.datasource.driver-class-name=com.mysql.jdbc.Driver
      spring.datasource.username=${APB_DB_USER}
      spring.datasource.password=${APB_DB_PASSWORD}
      spring.jpa.hibernate.ddl-auto=create