---
- name: Solve Lab 8
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
  - ../vars.yml
      
  tasks:
    - name: create temporary git directory
      tempfile:
        state: directory
        prefix: cd-infra-git
      register: git_dir

    - name: clone cd-infra git repository to {{ git_dir.path }}
      shell: "git clone http://{{ gogs_user }}:{{ gogs_password }}@{{ gogs_hostname }}/{{ gogs_user }}/cd-infra.git"
      args:
        chdir: "{{ git_dir.path }}"

    - name: create release jenkinsfile
      copy:
        src: Jenkinsfile.catalog-prod
        dest: "{{ git_dir.path }}/cd-infra/Jenkinsfile.catalog-prod"

    - name: push deploy catalog jenkinsfile to cd-infra git repository
      shell: |
        git config user.email "rhdeveloper@redhat.com"
        git config user.name "rh-developer"
        git add Jenkinsfile.catalog-prod
        git commit -m "canary prod pipeline added"
        git push origin master
      args:
        chdir: "{{ git_dir.path }}/cd-infra"

    - name: process catalog deploy pipeline template
      template:
        src: pipeline.yml.j2
        dest: "{{ git_dir.path }}/pipelne.yml"

    - name: create catalog deploy pipeline
      shell: "oc create -f {{ git_dir.path }}/pipelne.yml -n {{ cicd_project}}"
      ignore_errors: true
