- name: encode bind credentials
  asb_encode_binding:
    fields:
      DB_SERVICE_NAME: "{{service_name}}"
      DB_SERVICE_PORT: "{{db_port}}"
      DB_USER: "{{ mysql_user }}"
      DB_PASSWORD: "{{ mysql_password }}"
      DB_NAME: "{{ mysql_database }}"
      DB_ROOT_PASSWORD: "{{ mysql_root_password }}"
