apiVersion: v1
kind: Template
metadata:
  annotations:
    description: CoolStore Microservices - Catalog Deployment Template
    iconClass: icon-java
    tags: microservice,jboss,spring
  name: catalog-deployment
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: coolstore
      component: catalog
  spec:
    replicas: 1
    selector:
      app: coolstore
      component: catalog
      deploymentconfig: catalog
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: coolstore
          component: catalog
          deploymentconfig: catalog
        name: ${APP_NAME}
      spec:
        containers:
        - image: catalog
          imagePullPolicy: Always
          name: ${APP_NAME}
          envFrom:
          - secretRef:
              name: catalog-mysql-credentials
            prefix: SVCAT_
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: catalog:${IMAGE_VERSION}
          namespace: ${IMAGE_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: coolstore
      component: catalog
    name: ${APP_NAME}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: catalog
parameters:
- displayName: Catalog Service Name
  name: APP_NAME
  required: true
  value: catalog
- displayName: Image Version
  description: Catalog image version to deploy
  name: IMAGE_VERSION
  required: true
  value: latest
- displayName: Image Namespace
  description: The namespace to push the built Catalog images to
  name: IMAGE_NAMESPACE
  